---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[aspect_hostname::default]
    attributes:
      set_fqdn: test.example.com
  - name: wildcard
    run_list:
      - recipe[aspect_hostname::default]
    provisioner:
      solo_rb:
        node_name: test
    attributes:
set_fqdn: '*.example.com'
